// Mocks generated by Mockito 5.4.5 from annotations
// in mvvm_provider_starter/test/repository/post_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:mvvm_provider_starter/models/api_response.dart' as _i3;
import 'package:mvvm_provider_starter/models/post_model.dart' as _i7;
import 'package:mvvm_provider_starter/services/post_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResponse_1<T, V> extends _i1.SmartFake
    implements _i3.ApiResponse<T, V> {
  _FakeApiResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostService extends _i1.Mock implements _i4.PostService {
  MockPostService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.ApiResponse<List<_i7.PostModel>, String>> fetchPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPosts, []),
            returnValue:
                _i6.Future<_i3.ApiResponse<List<_i7.PostModel>, String>>.value(
                  _FakeApiResponse_1<List<_i7.PostModel>, String>(
                    this,
                    Invocation.method(#fetchPosts, []),
                  ),
                ),
          )
          as _i6.Future<_i3.ApiResponse<List<_i7.PostModel>, String>>);
}
